### ISSUE TITLE
serviceaccount kboom-sa and ImagePullBackOff

### ISSUE THREAD

**Issue by arashkaffamanesh** [mhausenblas/kboom#1]
Thanks for the nice work Michael!

After creating a service account named kboom-sa (whic is missing), I'm getting:

```
$ k logs kboom-trd2r
Error from server (BadRequest): container "kboom" in pod "kboom-trd2r" is waiting to start: trying and failing to pull image
```
seems ecr needs proper auth :-)

```
$ k describe pod kboom-trd2r
Failed to pull image "661776721573.dkr.ecr.us-east-2.amazonaws.com/kboom:latest": rpc 

error: code = Unknown desc = Error response from daemon: Get 

https://661776721573.dkr.ecr.us-east-2.amazonaws.com/v2/kboom/manifests/latest: no basic auth credentials
```

And

```
k create -f permissions.yaml
```

is needed.

**Comment by mhausenblas** [comment]
Thanks a lot @arashkaffamanesh and yeah, doh, need to fix ECR access. The permissions setup is explained in [install](https://github.com/mhausenblas/kboom#install) though ;)

**Comment by mhausenblas** [comment]
Should work now (a temporary fix, but …) so can you please try again @arashkaffamanesh?

**Comment by arashkaffamanesh** [comment]
It works like a charm! Thanks again for the brilliant work!

```
$ ./kubectl-kboom results
Server Version: v1.13.5
Running a scale test, launching 10 pod(s) with a 14s timeout ...

-------- Results --------
Overall pods successful: 6 out of 10
Total runtime: 14.229769666s
Fastest pod: 6.009329057s
Slowest pod: 13.011650419s
p50 pods: 10.06318941s
p95 pods: 13.011650419s
```

**Comment by mhausenblas** [comment]
Coolio and thanks again for the alpha testing, much appreciated :)

**Comment by arashkaffamanesh** [comment]
Only a minor issue in README:

```
kubectl kboom generate
kubectl kboom results

should be (dash is missing)

kubectl-kboom generate ...
kubectl-kboom results
```

**Comment by mhausenblas** [comment]
Actually, both is valid :)

Unless you're using a very old `kubectl` version that doesn't support the binary plugins, see also https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/

**Comment by arashkaffamanesh** [comment]
Yes, my issue was, I missed to move kubectl-kboom to /usr/local/bin on my path and it's clear `kubectl kboom results` can't work. Thanks again!
