### ISSUE TITLE
custom image instead of busybox

### ISSUE THREAD

**Issue by colmm99** [mhausenblas/kboom#6]
Is it possibly to provide a different image than busybox on the cli?

**Comment by mhausenblas** [comment]
It is currently not possible. However, the feature I want to add next is support for custom resources. This will in fact allow you to launch any kind of resource, something along the line of (in terms of DX still not sure): `--load=file://myresource.yaml:10`.

**Comment by colmm99** [comment]
Great stuff, I look forward to using it.
